# Generated by Django 2.2.24 on 2022-09-15 08:49

from django.db import migrations
import phonenumbers
from phonenumbers.phonenumberutil import NumberParseException


def normalize_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        try:
            parsed_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        except NumberParseException:
            continue
        if not phonenumbers.is_valid_number(parsed_number):
            continue
        flat.owner_pure_phonenumber = phonenumbers.format_number(
                                        parsed_number,
                                        phonenumbers.PhoneNumberFormat.E164
                                                            )
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phonenumber'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_number)
    ]
