# Generated by Django 2.2.28 on 2022-09-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20220915_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО владельца')),
                ('owner_number', models.CharField(max_length=50, verbose_name='Номер владельца')),
                ('owner_pure_number', models.CharField(blank=True, max_length=50, verbose_name='Нормализованный номер владельца')),
                ('owned_flats', models.ManyToManyField(related_name='owners', to='property.Flat', verbose_name='Квартиры в собственности')),
            ],
        ),
    ]
