# Generated by Django 2.2.28 on 2022-09-15 17:02

from django.db import migrations


def fill_owner_model(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
                  migrations.RunPython(fill_owner_model)
    ]
