# Generated by Django 2.2.28 on 2022-09-15 17:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20220915_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='name',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owner_number',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owner_pure_number',
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_pure_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Нормализованный номер владельца'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owners_phonenumber',
            field=models.CharField(default='', max_length=20, verbose_name='Номер владельца'),
            preserve_default=False,
        ),
    ]
