# Generated by Django 2.2.24 on 2022-09-16 06:30

from django.db import migrations


def fill_owner_flat_link(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all().iterator():
        owner, _ = Owner.objects.get_or_create(
                                owner=flat.owner,
                                owners_phonenumber=flat.owners_phonenumber,
                                owner_pure_phonenumber=flat.owner_pure_phonenumber,
        )
        owner.owned_flats.add(flat)
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20220916_0918'),
    ]

    operations = [
        migrations.RunPython(fill_owner_flat_link)
    ]
